CREATE DATABASE STU
CREATE TABLE ST_INFO(ROLL_NO INT NOT NULL PRIMARY KEY,
ST_CLASS VARCHAR(20) NOT NULL, 
ST_RESULT FLOAT NOT NULL, 
ST_MOBILE NUMERIC NOT NULL UNIQUE,
ST_CITY CHAR(20) NOT NULL, 
ST_NAME CHAR(50) NOT NULL);
SELECT * FROM ST_INFO
INSERT INTO ST_INFO VALUES(1, 10, 80, 7852369858, 'MUMBAI','RUTVIK');
INSERT INTO ST_INFO VALUES(2, 10, 85, 7852369859, 'DUBAI','RUTUJA');
INSERT INTO ST_INFO VALUES(3, 10, 83, 7852369857, 'PUNE','RUPESH');
INSERT INTO ST_INFO VALUES(4, 11, 70, 7852369856, 'MAHAD','RUTUPARN');
INSERT INTO ST_INFO VALUES(5, 11, 90, 7852369855, 'MUMBAI','REKHA');
INSERT INTO ST_INFO VALUES(6, 11, 85, 7852369854, 'PUNE','RADHIKA');
INSERT INTO ST_INFO VALUES(7, 12, 60, 7852369853, 'NASHIK','RAAJ');
INSERT INTO ST_INFO VALUES(8, 12, 62, 7852369852, 'JALGAV','RAMU');
INSERT INTO ST_INFO VALUES(9, 12, 55, 7852369851, 'MUMBAI','RAMESH');
INSERT INTO ST_INFO VALUES(10, 12, 50, 7852369850, 'PUNE','MOHINI');
SELECT ROLL_NO, ST_NAME, ST_RESULT FROM ST_INFO WHERE ST_RESULT>65;
SELECT ROLL_NO, ST_NAME, ST_CITY FROM ST_INFO WHERE ST_CITY='MUMBAI';

CREATE DATABASE EMP;
CREATE TABLE EMP_INF(EMP_ID INT NOT NULL, EMP_NAME CHAR(50) NOT NULL,
EMP_DESIGNATION VARCHAR(50) NOT NULL, EMP_DEPARTMENT CHAR(20) NOT NULL,
EMP_SALARY INT NOT NULL, EMP_AGE INT NOT NULL, EMP_CITY CHAR(20) NOT NULL);
SELECT * FROM EMP_INF
ALTER TABLE EMP_INF ADD PRIMARY KEY (EMP_ID);
ALTER TABLE EMP_INF ADD CHECK (EMP_AGE>20);
ALTER TABLE EMP_INF ADD CONSTRAINT DF_CITY DEFAULT 'MUMBAI' FOR EMP_CITY;
INSERT INTO EMP_INFO VALUES(1, 'RUTVIK', 'PRODUCTION', 'R&D', 50000, 25,'MUMBAI');
INSERT INTO EMP_INFO VALUES(2, 'RUTUJA', 'PRODUCTION', 'R&D', 55000, 25,'MUMBAI');
INSERT INTO EMP_INFO VALUES(3, 'RUTUPARN', 'TECHNICAL', 'R&D', 60000, 25,'MUMBAI');
INSERT INTO EMP_INFO VALUES(4, 'RUPESH', 'TECHNICAL', 'R&D', 19000, 25, 'MUMBAI');
INSERT INTO EMP_INFO VALUES(5, 'RUPALI', 'TECHNICAL', 'R&D', 100000, 25, 'MUMBAI');
INSERT INTO EMP_INFO VALUES(6, 'REKHA', 'HR', 'ADMIN', 75000, 25, 'MUMBAI');
INSERT INTO EMP_INFO VALUES(7, 'RAMESH', 'HR', 'ADMIN', 20000, 25, 'MUMBAI');
INSERT INTO EMP_INFO VALUES(8, 'RAVI', 'HR', 'PRODUCTION', 10000, 25, 'MUMBAI');
INSERT INTO EMP_INFO VALUES(9, 'RAJENDRA', 'ADMINISTRATION', 'PRODUCTION',15000, 25, 'MUMBAI');
INSERT INTO EMP_INFO VALUES(10, 'MOHINI', 'ADMINISTRATION', 'PRODUCTION', 17000,25, 'MUMBAI');
SELECT EMP_ID, EMP_NAME, EMP_DESIGNATION FROM EMP_INFO WHERE EMP_DESIGNATION='PRODUCTION';
SELECT EMP_ID, EMP_NAME, EMP_SALARY FROM EMP_INFO WHERE EMP_SALARY<20000;
SELECT EMP_NAME, EMP_DESIGNATION, EMP_SALARY FROM EMP_INFO WHERE EMP_CITY='MUMBAI'
SELECT EMP_NAME, EMP_CITY, EMP_AGE FROM EMP_INFO WHERE EMP_DEPARTMENT='PRODUCTION'